# Operator installation via OLM
operator2:
  # Set to true to install the operator
  # Set to false if operator is already installed on cluster
  enabled: true
  name: cloudnative-pg
  namespace: cnpg-system
  channel: stable-v1
  source: certified-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic