# Operator installation via OLM
operator1:
  # Set to true to install the operator
  # Set to false if operator is already installed on cluster
  enabled: true
  name: konveyor
  namespace: konveyor-tackle
  channel: konveyor-0.9
  source: konveyor
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
