{{- if .Values.operator3.enabled }}
{{- $existingSub := lookup "operators.coreos.com/v1alpha1" "Subscription" .Values.operator3.namespace .Values.operator3.name }}
{{- if not $existingSub.metadata }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operator3.name }}-og
  namespace: {{ .Values.operator3.namespace }}
spec:
  # targetNamespaces を指定しない、または自身の Namespace を指定することで
  # その Namespace 内で Operator が動作するようになります
  targetNamespaces: {{ .Values.operator3.namespace }}
---
# Install operator via OLM Subscription
# Skipped automatically if subscription already exists
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator3.name }}
  namespace: {{ .Values.operator3.namespace }}
  labels:
    demo.redhat.com/application: "operator3"
spec:
  channel: {{ .Values.operator3.channel }}
  installPlanApproval: {{ .Values.operator3.installPlanApproval }}
  name: {{ .Values.operator3.name }}
  source: {{ .Values.operator3.source }}
  sourceNamespace: {{ .Values.operator3.sourceNamespace }}
{{- end }}
{{- end }}
