# Operator installation via OLM
operator4:
  # Set to true to install the operator
  # Set to false if operator is already installed on cluster
  enabled: true
  name: rhbk-operator
  namespace: keycloak-operator
  channel: stable-v26
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic